#!/bin/bash

# 7/24/2019 by ding
# source code location
base=~/sea
cd ~
mkdir code
# the running jar file and its backups
cd sea
mkdir jars

# ops for operation
# ops/log, generated by your application
# ops/runhere, where you run app in nohup manner
# ops/tomcat, springboot built-in tomcat temp files 
mkdir -p ops/logs ops/runhere ops/tomcat

# verify
echo "your ~"
ls ..

echo "your sea"
ls 

echo "your ops"
tree ops

